### ISSUE TITLE
Syntax errors; cannot run chex_latex.pl

### ISSUE THREAD

**Issue by rindPHI** [erich666/chex_latex#4]
Hi!

I just tried this very promising tool. Unfortunately, I get a number of errors. First, there was an overwhelming bunch of lines such as the following:

    Global symbol "$lctwoline" requires explicit package name (did you forget to declare "my $lctwoline"?) at chex_latex.pl line 2674.

Removing `use strict` boiled this down to

    Scalar found where operator expected at chex_latex.pl line 839, near "$!$infigure"
            (Missing operator before $infigure?)
    syntax error at chex_latex.pl line 839, near "$!$infigure "
    syntax error at chex_latex.pl line 2771, near "} else"
    syntax error at chex_latex.pl line 2776, near "}"
    syntax error at chex_latex.pl line 2787, near "}"
    Can't redeclare "my" in "my" at chex_latex.pl line 2792, near "my"
    syntax error at chex_latex.pl line 2805, near "}"
    syntax error at chex_latex.pl line 2815, near "}"
    Can't redeclare "my" in "my" at chex_latex.pl line 2820, near "my"
    syntax error at chex_latex.pl line 2874, near "}"
    Can't redeclare "my" in "my" at chex_latex.pl line 2878, near "my"
    chex_latex.pl has too many errors.

I'm calling the script using `perl chex_latex.pl`, my perl version is 5.26.1, I'm running Ubuntu 18.04. Thanks for any help with this issue, I'd love to try out the tool!

**Comment by rindPHI** [comment]
I changed line 839 from

    if( !$ok && !$textonly && !$!$infigure && $theline =~ /\d \d\d\d/ ) {

to

    if( !$ok && !$textonly && !$infigure && $theline =~ /\d \d\d\d/ ) {
    
which seems to solve it. Was that a typo?

**Comment by erich666** [comment]
That's exactly the fix needed, some finger fumble on my part. Thanks for reporting this one, and shame on me for not doing one final sanity test before checking in. Anyway, it's now fixed in the repo, too.

**Comment by erich666** [comment]
Oh, and I hope you find the script of use. It natters a bit, but simply delete or comment out the warnings you don't care about. It's caught a lot of my own goofs or subtle latex changes needed over the years.
